name: Build on ubuntu

on:
  push:
  pull_request:
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-20.04 ]
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-go@v4.0.1
      - uses: actions/checkout@v3
      - name: Build the project
        run: go build .
