name: Build on ubuntu

on:
  push:
  pull_request:
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-20.04 ]
        # We are using some features added only in go 1.20, that's
        # why we cannot support any other versions at the moment
        gover: [ "1.20" ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-go@v4.0.1
        with:
          go-version: ${{ matrix.gover }}
      - uses: actions/checkout@v3
      - name: Build the project
        run: go build .
